steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '-t'
      - '${_IMAGE}'
      - '.'
images:
  - '${_IMAGE}'
substitutions:
  _IMAGE: 'australia-southeast1-docker.pkg.dev/ecodiaos/ecodiaos/frontend:latest'
  _NEXT_PUBLIC_API_URL: 'https://ecodiaos-core-929871567697.australia-southeast1.run.app'
